default: &default
  adapter: <%= ENV['ADAPTER'] %>
  encoding: unicode
  url:  <%= ENV['DATABASE_URL'] %>
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: <%= ENV['DB'] %>
test:
  <<: *default
  database: <%= ENV['DB_TEST'] %>
production:
  <<: *default
  database: <%= ENV['DB'] %>
